networks:
  personal:

services:
  nginx:
    container_name: nginx
    image: nginx:1.27.3
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl-certificates/public.crt:/etc/ssl/public.crt"
      - "./ssl-certificates/private.key:/etc/ssl/private.key"
      - "./ssl-certificates/ssl.pass:/etc/ssl/ssl.pass"
    ports:
      - 443:443
    networks:
      - personal

  personal-portfolio:
    container_name: personal-portfolio
    image: ayrtonfidel9/personal-portfolio:v1.2
    restart: always
    networks:
      - personal
