networks:
  personal:

services:
  nginx:
    image: nginx:1.27.3
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl-certificates/public.crt:/etc/ssl/public.crt"
      - "./ssl-certificates/private.key:/etc/ssl/private.key"
    #command: bash -c "restorecon -v -R /etc/ssl"
    ports:
      - 443:443
      - 80:80
    networks:
      - personal

  personal-portfolio:
    build: .
    restart: always
    networks:
      - personal
