networks:
  personal:

services:
  nginx:
    image: nginx:1.27.3
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/ssl-certificates/public.pem:/etc/ssl/public.pem"
      - "/ssl-certificates/private.pem:/etc/ssl/private.pem"
    #command: bash -c "restorecon -v -R /etc/ssl"
    ports:
      - 443:443
    networks:
      - personal

  personal-portfolio:
    build: .
    restart: always
    networks:
      - personal
